export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS'
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS'
export const LOAD_LIVE_EVENTS_DATA_SUCCESS = 'LOAD_LIVE_EVENTS_DATA_SUCCESS'
export const LOAD_PRIMARY_MARKET_DATA_SUCCESS =
  'LOAD_PRIMARY_MARKET_DATA_SUCCESS'
export const LOAD_EVENT_FULL_DETAILS_SUCCESS = 'LOAD_EVENT_FULL_DETAILS_SUCCESS'

export const ADD_BETSLIP_SUCCESS = 'ADD_BETSLIP_SUCCESS'
export const REMOVE_BETSLIP_SUCCESS = 'REMOVE_BETSLIP_SUCCESS'
export const TOGGLE_EVENT_INTEREST_SUCCESS = 'TOGGLE_EVENT_INTEREST_SUCCESS'

//Websocket API Types
export const LIVE_EVENTS_DATA = 'LIVE_EVENTS_DATA'
export const MARKET_DATA = 'MARKET_DATA'
